### ISSUE TITLE
第154行的time.sleep(20)干啥的。。

### ISSUE THREAD

**Issue by 15921483570** [Seraphir/turtle-vectorgraph#1]
太邪恶了，差点让我以为这代码运行不了，电脑崩溃了。。😂

**Comment by LaoshuBaby** [comment]
同问，注释掉以后很快就能出结果，肉眼可见的绘制完。~~难不成方便录屏软件开始的等待时间的吗？（大雾）~~

**Comment by Seraphir** [comment]
你们大概是对的，我也忘了为什么会加这行……已经删掉了

**Comment by LaoshuBaby** [comment]
<del>一定是产品经理为了骗用户掏钱优化性能的阴谋！</del>

啊既然已经在 https://github.com/Seraphir/turtle-vectorgraph/commit/3132146d4949717c1f5d87239161287bac08ff58 里面修复了的话，就请作者大人关掉这个issue好了！φ(゜▽゜*)♪
